### ISSUE TITLE
Is there any idea about how to use Facade of use case to implement work_creat in FacadeSys?

### ISSUE THREAD

**Issue by Tseateen** [CSC207-UofT/course-project-group_003#101]
I'm a little bit confused about how to solve an issue that simplifies the creation step. Should we check users' input or just check their authority level and create work's level?

**Comment by Tseateen** [comment]
I got one idea which written in FacadeSysTest distributeWork. If there are any other ideas, pls tell me.

**Comment by Lily-alive** [comment]
would it be better to check their authority level first so if they do not have the level as high as required, they cannot create a work?
