### ISSUE TITLE
Naming Convention.

### ISSUE THREAD

**Issue by ChiehAnChang** [CSC207-UofT/course-project-group_003#229]
1. Use camel case instead of underscore.
2. Naming meaningful. For instance, use "employee"  not "e".
3. Watch the warning before every pull request.

**Comment by Lily-alive** [comment]
Got it: )

**Comment by kyle011223** [comment]
We have followed the three rules throughout Phase 2!

**Comment by PenguinKuo007** [comment]
I checked our code again, all of them are following naming convention :)
