### ISSUE TITLE
About Test Cases

### ISSUE THREAD

**Issue by Cathypei** [CSC207-UofT/course-project-group_003#259]
Which classes are more prior to write test cases for? Which classes are good on themselves (classes that do not need as much tests)? What do you guys think?

**Comment by Lily-alive** [comment]
I think we need to write test cases to test the FacadeSys as it is a pretty large class that delegates work to other classes:)

**Comment by kyle011223** [comment]
I have tested all the usecases that are indirectly called by the FacadeSys!
