### ISSUE TITLE
STILL HAVE PROBLEMS IN EXTEND WORK UI

### ISSUE THREAD

**Issue by PenguinKuo007** [CSC207-UofT/course-project-group_003#264]
as title, especially in the timestamp part of the code. I don't think it works for now. Maybe we should consider deleting it or someone has to fix it.

**Comment by PenguinKuo007** [comment]
dealing with long is a problem now, other functionality seems fine so far.

**Comment by kyle011223** [comment]
Yide have solved the timestamp part of the code. I also delete the timestamp part in KPICalculator and changed it to other method.
