### ISSUE TITLE
Work assigning method

### ISSUE THREAD

**Issue by Cathypei** [CSC207-UofT/course-project-group_003#268]
Do we have any work assigning method? When I wrote test cases that need to assign a group to a work, I'm not quite sure how to do it. Does creating a group already means that we assigned this group to a work (when creating group we need to give it a work id)? Because when I tried to find how to modify a work's state, the method does not ask for  the group id. 

PS: The test cases I was struggling with are in PersonalManager_test, but there is no error. Seems like I was doing it right but I am still not sure...

**Comment by Tseateen** [comment]
I will help.

**Comment by kyle011223** [comment]
I have finished the test for PersonalManager_test, and usescases test related to assigned group to work.
