### ISSUE TITLE
What is the form of EndTime?

### ISSUE THREAD

**Issue by kyle011223** [CSC207-UofT/course-project-group_003#277]
Before, the form of EndTime is defined as the string that follows "YYYY/MM/DD HH:MM", and I have followed this convention to construct the code from KPIcalculator. However, now the  form of EndTime is defined to be "String Need to be the form of timestamp". This is quite vague. Could someone elaborate?

**Comment by Tseateen** [comment]
Timestamp can translate to Date as "yyyy-MM-dd", i will show you detail in code.
