### ISSUE TITLE
Questions about TestCase

### ISSUE THREAD

**Issue by kyle011223** [CSC207-UofT/course-project-group_003#281]
I think I have written all the UseCasesTestCases that are used in FacadeSys. Please double check in case I have missed anything. I have made sure that all TestCases pass EXCEPT for the GroupManager_test since I think there are some bugs. Please take some time to see what went wrong. Also, for the PersonalManager_test, there are still some more cases that could be tested (such as PartTimeEmployee salary and KPI test). Please add more tests if available so it would be more complete.

Lastly, do we need to write testcases for Framework and InterfaceAdapter as the TA suggested in Phase 1? If so, what methods and how excatly should we test them?

**Comment by PenguinKuo007** [comment]
I was adding test case for controllers. There are two controllers left.
I don't think we're going to test on interface because none of them return value

**Comment by kyle011223** [comment]
Thanks a lot! Great effort!!
