### ISSUE TITLE
Account List

### ISSUE THREAD

**Issue by ChiehAnChang** [CSC207-UofT/course-project-group_003#91]
Now, we have a problem with our AccountManager.
It is hard to read file form data base to AccountManager because we use Map to store data in AccountManager.
Suggest Solution From Luke And Me:
step 1: Make a new Use case stores all Userable object. i.e LoginList.
step 2: Make a new use case store all employee object.
step 3: Both of them implements iterator design pattern so that we can read data through iterator and store into corresponding place.

Please let me know any suggestion.

**Comment by Tseateen** [comment]
1

**Comment by Tseateen** [comment]
I agree

**Comment by Lily-alive** [comment]
Sure, I agree with the solutions. One good thing is that we can also use the iterator design pattern to make our code to make code structured.

**Comment by kyle011223** [comment]
I think that implementing iterator design pattern is a good idea.

**Comment by PenguinKuo007** [comment]
I agree with the idea. We can make use of IDs to achieve this operation.
