### ISSUE TITLE
About Group iterator

### ISSUE THREAD

**Issue by Cathypei** [CSC207-UofT/course-project-group_003#92]
We still think about implementing the iterator in the Group class. However, now it seemed not necessary in this class since we are going to add an attribute that stored the finished work in each employee's work information. Also, since we are thinking to create an individual class that store the work list. Should we instead implement the iterator in the WorkList class?

**Comment by Tseateen** [comment]
I dont think we need an iterator for Groups, since Group only exist with Group Work. No Work, no Group; no Group, Work still can exist.
