### ISSUE TITLE
Position

### ISSUE THREAD

**Issue by ChiehAnChang** [CSC207-UofT/course-project-group_003#93]
I am coding on employee list, and I found a wired thing.

Our part-time employee does not have position.

Can someone confirm this?

**Comment by kyle011223** [comment]
Yes. I think that when we first discussed this class, the conclusion was that only full-time employees have position but part-time employees do not (since they only work part-time). Maybe we could discuss more about this in our next group meeting

**Comment by PenguinKuo007** [comment]
I don't think part-employees have position since they are not formal employee as full-tine employee

**Comment by Tseateen** [comment]
They only should have a department, not a position. Since part-time is their position.

**Comment by Lily-alive** [comment]
Yes, from my point of view, the part-time workers are not official workers and they are doing the basic work like data collections for the company to run smoothly in their daily schedule. So, maybe they don't need a specific department cause they are very likely to work for the IT department with the code inside the tech company.
